### ISSUE TITLE
add WN/MZ - Aschendorf

### ISSUE THREAD

**Issue by addnwn** [tobimori/paywallr#15]
Hello,
can you please include the following page for learning purposes?
www.wn.de
this sites belong to the Aschendorff Verlag, www.muensterlandzeitung.de already included.
Thanks

**Comment by tobimori** [comment]
I sadly can't include the page as they are using another content management system whose paywall doesn't expose the content to non-paying users (according to my quick tests). If you find a way to get access to the content, feel free to reopen the issue and send me details about it.
