### ISSUE TITLE
Kölner Stadt-Anzeiger

### ISSUE THREAD

**Issue by tsutey** [tobimori/paywallr#7]
Hallo zusammen,

Folgender Artikel lässt sich bei mir nicht komplett lesen

https://www.ksta.de/koeln/streifzug-durch-die-partymeilen-seltsame-koelner-naechte-in-zeiten-von-corona-36481462

Viele Grüße

**Comment by tobimori** [comment]
Hi, danke fuer dein Issue.
In der alten und neuen Version laedt der Artikel einwandfrei. Kannst du versuchen Ublock Origin zu verwenden und einfach mal den Cache zu leeren?

Sonst duerfte es spaetestens dann mit Version 2.0, an der ich gerade arbeite, funktionieren, da ich da den Artikel anders bekomme.

**Comment by tsutey** [comment]
Hatte den ABP zusammen mit dem Ublock installiert, habe den ABP deinstalliert und den Cache geleert danach funktionierte auch der Kölner Stadt-Anzeiger. Vermutlich funktionieren die beiden Blocker zusammen nicht sinnvoll...

**Comment by tobimori** [comment]
Super :)
