### ISSUE TITLE
Breaks Coronamap on morgenpost.de

### ISSUE THREAD

**Issue by merlinschumacher** [tobimori/paywallr#8]
This page doesn't work anymor when the add-on is enabled.
https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/

**Comment by tobimori** [comment]
Hi, the new version I'm currently working on will fix this. Please deactivate the addon for now when accessing the map. Thanks for your notice though!

**Comment by tobimori** [comment]
Hi, the new version I'm currently working on will fix this. Thanks for your notice though!
